# Generated by Django 5.0.7 on 2024-07-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coordinator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coordinator_name", models.CharField()),
                ("coordinator_email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name="affiliation",
            name="coordinator",
        ),
    ]
