# Generated by Django 5.0.7 on 2024-07-19 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliations", "0002_coordinator_remove_affiliation_coordinator"),
    ]

    operations = [
        migrations.AddField(
            model_name="coordinator",
            name="affiliation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="affiliations.affiliation",
            ),
        ),
        migrations.AlterField(
            model_name="affiliation",
            name="clinvar_submitter_ids",
            field=models.CharField(default="Submitter ID"),
        ),
    ]
