# Generated by Django 5.0.7 on 2024-07-19 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliations", "0003_coordinator_affiliation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affiliation",
            name="clinvar_submitter_ids",
            field=models.CharField(),
        ),
    ]
