# Generated by Django 5.0.7 on 2024-07-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliations", "0004_alter_affiliation_clinvar_submitter_ids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coordinator",
            name="coordinator_name",
            field=models.CharField(max_length=200),
        ),
    ]
