# Generated by Django 5.0.7 on 2024-07-22 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliations", "0005_alter_coordinator_coordinator_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="affiliation",
            name="approvers",
        ),
        migrations.CreateModel(
            name="Approvers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("approvers", models.CharField()),
                (
                    "affiliation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="affiliations.affiliation",
                    ),
                ),
            ],
        ),
    ]
