# Generated by Django 5.0.7 on 2024-07-22 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("affiliations", "0006_remove_affiliation_approvers_approvers"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Approvers",
            new_name="Approver",
        ),
        migrations.RenameField(
            model_name="approver",
            old_name="approvers",
            new_name="approver",
        ),
    ]
