# Generated by Django 5.1.5 on 2025-03-31 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliations", "0035_affiliation_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affiliation",
            name="clinical_domain_working_group",
            field=models.CharField(
                choices=[
                    ("NONE", "None"),
                    ("CARDIOVASCULAR", "Cardiovascular"),
                    ("HEARING_LOSS", "Hearing Loss"),
                    ("HEMOSTASIS_THROMBOSIS", "Hemostasis/Thrombosis"),
                    ("HEREDITARY_CANCER", "Hereditary Cancer"),
                    ("IMMUNOLOGY", "Immunology"),
                    ("INBORN_ERR_METABOLISM", "Inborn Errors of Metabolism"),
                    ("KIDNEY_DISEASE", "Kidney Disease"),
                    ("NEURODEVELOPMENTAL_DISORDER", "Neurodevelopmental Disorders"),
                    ("NEUROLOGICAL_DISORDERS", "Neurological Disorders"),
                    ("OCULAR", "Ocular"),
                    ("OTHER", "Other"),
                    ("PULMONARY", "Pulmonary"),
                    ("RASOPATHY", "RASopathy"),
                    ("REPRODUCTION_AND_PREGNANCY", "Reproduction and Pregnancy"),
                    ("RHEUMA_AUTO_DISEASE", "Rheumatologic Autoimmune Disease"),
                    ("SKELETAL_DISORDERS", "Skeletal Disorders"),
                    ("SOMATIC_CANCER", "Somatic Cancer"),
                ],
                verbose_name="CDWG",
            ),
        ),
    ]
