# Generated by Django 5.1.4 on 2025-06-18 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliations", "0036_alter_affiliation_clinical_domain_working_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicalDomainWorkingGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        # Rename old CharField to keep its data
        migrations.RenameField(
            model_name="affiliation",
            old_name="clinical_domain_working_group",
            new_name="clinical_domain_working_group_old",
        ),
        migrations.AddField(
            model_name="affiliation",
            name="clinical_domain_working_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="affiliations",
                to="affiliations.clinicaldomainworkinggroup",
            ),
        ),
    ]
