# Generated by Django 5.1.4 on 2025-06-18 21:32

from django.db import migrations


def populate_cdwg(apps, schema_editor):
    CDWG = apps.get_model("affiliations", "ClinicalDomainWorkingGroup")
    Affiliation = apps.get_model("affiliations", "Affiliation")

    cdwg_map = {
        "NONE": "None",
        "HEARING_LOSS": "Hearing Loss",
        "CARDIOVASCULAR": "Cardiovascular",
        "HEMOSTASIS_THROMBOSIS": "Hemostasis/Thrombosis",
        "HEREDITARY_CANCER": "Hereditary Cancer",
        "IMMUNOLOGY": "Immunology",
        "INBORN_ERR_METABOLISM": "Inborn Errors of Metabolism",
        "KIDNEY_DISEASE": "Kidney Disease",
        "NEURODEVELOPMENTAL_DISORDER": "Neurodevelopmental Disorders",
        "NEUROLOGICAL_DISORDERS": "Neurological Disorders",
        "OCULAR": "Ocular",
        "OTHER": "Other",
        "PULMONARY": "Pulmonary",
        "RASOPATHY": "RASopathy",
        "REPRODUCTION_AND_PREGNANCY": "Reproduction and Pregnancy",
        "RHEUMA_AUTO_DISEASE": "Rheumatologic Autoimmune Disease",
        "SKELETAL_DISORDERS": "Skeletal Disorders",
        "SOMATIC_CANCER": "Somatic Cancer",
    }

    # Create new CDWG records
    for code, name in cdwg_map.items():
        CDWG.objects.get_or_create(code=code, defaults={"name": name})

    # Migrate old string field to FK
    for affiliation in Affiliation.objects.all():
        if affiliation.clinical_domain_working_group_old:
            try:
                cdwg = CDWG.objects.get(
                    code=affiliation.clinical_domain_working_group_old
                )
                affiliation.clinical_domain_working_group = cdwg
                affiliation.save()
            except CDWG.DoesNotExist:
                pass


class Migration(migrations.Migration):
    dependencies = [
        ("affiliations", "0037_clinicaldomainworkinggroup_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_cdwg, reverse_code=migrations.RunPython.noop),
    ]
