# Generated by Django 5.1.4 on 2025-06-18 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("affiliations", "0038_auto_20250618_2132"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="affiliation",
            name="clinical_domain_working_group_old",
        ),
    ]
