# Generated by Django 5.1.4 on 2025-06-19 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliations", "0039_auto_20250618_2141"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affiliation",
            name="clinical_domain_working_group",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="affiliations",
                to="affiliations.clinicaldomainworkinggroup",
                verbose_name="Clinical Domain Working Group",
            ),
            preserve_default=False,
        ),
    ]
