# Generated by Django 5.1.4 on 2025-06-19 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliations", "0040_alter_affiliation_clinical_domain_working_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinicaldomainworkinggroup",
            name="code",
            field=models.CharField(
                help_text="A less than 30 character, unique identifier code (e.g., 'NONE', 'RHEUMA_AUTO_DISEASE').",
                max_length=30,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="clinicaldomainworkinggroup",
            name="name",
            field=models.CharField(
                help_text="The full name of the clinical domain working group.",
                max_length=255,
            ),
        ),
    ]
