# Generated by Django 5.1.4 on 2025-06-19 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("affiliations", "0041_alter_clinicaldomainworkinggroup_code_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clinicaldomainworkinggroup",
            options={
                "verbose_name": "Clinical Domain Working Group",
                "verbose_name_plural": "Clinical Domain Working Groups",
            },
        ),
    ]
