# Generated by Django 5.1.5 on 2025-06-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliations", "0042_alter_clinicaldomainworkinggroup_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinicaldomainworkinggroup",
            name="code",
            field=models.CharField(
                help_text=" A less than 30 character, unique identifier code\n        (e.g., 'NONE', 'RHEUMA_AUTO_DISEASE').",
                max_length=30,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="clinicaldomainworkinggroup",
            name="name",
            field=models.CharField(
                help_text="The full name of the clinical domain\n        working group.",
                max_length=255,
            ),
        ),
    ]
