# Generated by Django 5.1.5 on 2025-07-03 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliations", "0043_alter_clinicaldomainworkinggroup_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affiliation",
            name="expert_panel_id",
            field=models.IntegerField(
                blank=True, null=True, unique=True, verbose_name="Expert Panel ID"
            ),
        ),
        migrations.AlterField(
            model_name="affiliation",
            name="members",
            field=models.CharField(blank=True, null=True),
        ),
    ]
