# Generated by Django 5.1.5 on 2025-07-03 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliations", "0044_alter_affiliation_expert_panel_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affiliation",
            name="expert_panel_id",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Expert Panel ID"
            ),
        ),
    ]
