# Generated by Django 5.1.5 on 2025-07-07 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("affiliations", "0045_alter_affiliation_expert_panel_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clinicaldomainworkinggroup",
            name="code",
        ),
    ]
