# Generated by Django 5.1.5 on 2025-07-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliations", "0046_remove_clinicaldomainworkinggroup_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="affiliation",
            name="uuid",
            field=models.CharField(
                default="uuid", unique=True, verbose_name="GPM UUID"
            ),
            preserve_default=False,
        ),
    ]
