# Generated by Django 5.1.5 on 2025-07-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliations", "0047_affiliation_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affiliation",
            name="uuid",
            field=models.CharField(
                blank=True, null=True, unique=True, verbose_name="GPM UUID"
            ),
        ),
    ]
