# Generated by Django 5.2.4 on 2025-07-31 21:02
from django.db import migrations


def migrate_old_api_keys(apps, schema_editor):
    OldAPIKey = apps.get_model("rest_framework_api_key", "APIKey")
    CustomAPIKey = apps.get_model("affiliations", "CustomAPIKey")

    for old_key in OldAPIKey.objects.all():
        CustomAPIKey.objects.update_or_create(
            id=old_key.id,
            defaults={
                "name": old_key.name,
                "prefix": old_key.prefix,
                "hashed_key": old_key.hashed_key,
                "created": old_key.created,
                "revoked": old_key.revoked,
                "expiry_date": old_key.expiry_date,
                "can_write": False,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("affiliations", "0047_customapikey"),
        ("rest_framework_api_key", "0005_auto_20220110_1102"),
    ]

    operations = [
        migrations.RunPython(migrate_old_api_keys),
    ]
