# Generated by Django 5.2.4 on 2025-08-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliations", "0048_migrate_api_keys"),
    ]

    operations = [
        migrations.AddField(
            model_name="affiliation",
            name="uuid",
            field=models.UUIDField(
                blank=True, null=True, unique=True, verbose_name="GPM UUID"
            ),
        ),
    ]
