# Generated by Django 5.2.4 on 2025-08-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliations", "0048_alter_affiliation_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affiliation",
            name="uuid",
            field=models.UUIDField(
                blank=True, null=True, unique=True, verbose_name="GPM UUID"
            ),
        ),
    ]
