# Generated by Django 5.2.4 on 2025-08-14 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("affiliations", "0048_migrate_api_keys"),
        ("affiliations", "0049_alter_affiliation_uuid"),
    ]

    operations = []
