# Generated by Django 5.0.6 on 2024-07-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Affiliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("affiliation_id", models.IntegerField()),
                ("name", models.CharField()),
                ("coordinator", models.CharField()),
                ("status", models.CharField()),
                ("type", models.CharField()),
                ("family", models.CharField()),
                ("members", models.CharField()),
                ("approvers", models.CharField()),
                ("clinvar_submitter_ids", models.CharField()),
            ],
        ),
    ]
